#!/usr/bin/python3

import os
from os import path

prime_path  = os.environ.get('PRIME_PATH') 
cfg_dir = path.join(prime_path, "xml")

for pr in ["mesi", "wu"]:
    for c in [1, 2, 4, 8, 16]:
          with open(path.join(cfg_dir, "bc_%s_c%d.xml") % (pr, c), 'w') as f:
              f.write("""\
<?xml version = "1.0" encoding = "utf-8" standalone = "yes"?>

<simulator>
    <num_prod_threads>%d</num_prod_threads>
    <num_cons_threads>%d</num_cons_threads>
    <max_msg_size>128</max_msg_size>
    <system>
       <dram_access_time>200</dram_access_time>
       <protocol>%d</protocol>
       <network>
          <inject_delay>1</inject_delay>
          <net_type>0</net_type>
          <link_delay>1</link_delay>
          <data_width>10</data_width>
          <header_flits>3</header_flits>
          <router_delay>0</router_delay>
       </network>
       <bus>
          <ratio>1</ratio>
          <bandwidth>32</bandwidth>
          <data_pkt_len>64</data_pkt_len>
          <unlim_bw>1</unlim_bw>
          <ctrl_pkt_len>8</ctrl_pkt_len>
       </bus>
       <verbose_report>1</verbose_report>
       <cache>
          <num_ways>8</num_ways>
          <access_time>2</access_time>
          <level>0</level>
          <share>1</share>
          <block_size>64</block_size>
          <size>65536</size>
       </cache>
       <cache>
          <num_ways>16</num_ways>
          <access_time>16</access_time>
          <level>1</level>
          <share>1</share>
          <block_size>64</block_size>
          <size>1048576</size>
       </cache>
       <num_cores>%d</num_cores>
       <page_size>4096</page_size>
       <page_miss_delay>200</page_miss_delay>
       <directory_cache>
          <num_ways>24</num_ways>
          <access_time>10</access_time>
          <level>0</level>
          <share>1</share>
          <block_size>64</block_size>
          <size>31457280</size>
       </directory_cache>
       <protocol_type>0</protocol_type>
       <tlb_enable>1</tlb_enable>
       <cpi_nonmem>0.25</cpi_nonmem>
       <tlb_cache>
          <num_ways>64</num_ways>
          <access_time>0</access_time>
          <level>0</level>
          <share>1</share>
          <block_size>1</block_size>
          <size>64</size>
       </tlb_cache>
       <freq>2.5</freq>
       <shared_llc>0</shared_llc>
       <num_levels>2</num_levels>
       <sys_type>1</sys_type>
       <max_num_sharers>6</max_num_sharers>
    </system>
    <syscall_cost>0</syscall_cost>
    <thread_sync_interval>128</thread_sync_interval>
</simulator>
""" % ((c if c < 2 else 2), (c if c < 8 else 8), (1 if pr == "wu" else 0), c))
